language: python
dist: focal  
python:
  - "3.10"   

before_install:
  - sudo apt-get update

install:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install telebot flask pymongo aiohttp

script:
  - chmod +x * && chmod +x sharp && python3 sharp.py
